### ISSUE TITLE
"this.exec is not a function" error in Webpack 5

### ISSUE THREAD

**Issue by Finesse** [jeerbl/webfonts-loader#121]
When webfonts-loader is used with Webpack 5 (that has been released recently), the loader emits an error "this.exec is not a function" and the Webpack build fails.

**Comment by kelunik** [comment]
See #122 for a working implementation.

**Comment by enrique-ramirez** [comment]
Hi! This is the last remaining package that needs compatibility before I can upgrade to webpack 5 on my project. Webpack 5 is really disruptive . Not sure why, really, but many packages I use dropped support for webpack 4 in favor of webpack 5 leaving me with a ton of outdated packages because I can't update yet (it's amazing how fast npm modules move!). I try to keep my packages updated since the longer one waits to update them, the hardest it becomes to do it.

Just commenting to give a bit of priority to #122 and thank @kelunik for the fast response!
