### ISSUE TITLE
HTML file not generated

### ISSUE THREAD

**Issue by ChetanGandhi** [jeerbl/webfonts-loader#138]
Current config have `writeFiles` set to `false`, which is correct, but now HTML file is not generated by `webfontsGenerator`. In order to let `webfontsGenerator` generate the HTML file, `writeFiles` need to be set to `true`. 

Setting `writeFiles` to `true` will break things hence the html file need to created as you do for the code points.

**Comment by gseidel** [comment]
When I read the history, it look like the ``writeFiles`` is a never ending story. I think it's right that #120 remove this option, because for a webpack loader this feature is unnecessary. On the other hand, to generate the html preview in the webpack build directory seems like a valid feature for that loader. But to do so, I guess we need to expose the html to the result in the ``@vusion/webfonts-generator``  in order to emit the html file into the build path.

**Comment by ChetanGandhi** [comment]
Agreed, unless @vusion/webfonts-generator add support to have html in result it's not possible to create the target file.

I will prefer to update the documentation and remove the html related config, but I will leave it to you to decide what's good.

Thanks.

**Comment by jeerbl** [comment]
Hi @ChetanGandhi, @gseidel,

I saw the PR on `webfonts-generator` has been merged, what exactly need to be done here in order to generate that file? Not sure exactly what should be done here as it seems to be a generator issue.

Jerome

**Comment by gseidel** [comment]
@jeerbl I will open a draft PR so we can further discuss what should be done here to fix this issue

**Comment by gseidel** [comment]
Waiting for @jeerbl to feedback or merge PR #140

**Comment by MoLow** [comment]
@gseidel thanks for this great package, 
is there a way for me to generate html files to the disk, and to using webpack emit files? my usecase is pretty similar to the usecase described in https://github.com/jeerbl/webfonts-loader/issues/145 - I want to expose typescript variables, to the disk.
is there a way to achieve this?
